site_name: ALPACA's documentation
plugins:
- mkdocstrings:
    handlers:
      pac_handler:
        bla: yes

nav:
  - "Getting Started": index.md
  - "Lua API": lua.md
  - "Scenes": scene.md
  - "Dialogs": dialogs.md
  - "Spine": spine.md
  - "Assets": asset_pipeline.md
  - "Made with ALPACA": made_with.md
