site_name: ALPACA's LUA Docs
plugins:
- mkdocstrings:
    handlers:
      pac_handler:
        bla: yes

nav:
  - "Getting Started": index.md
  - "LUA API": lua.md
  - "Assets": asset_pipeline.md
  - "Scenes": scene.md
  - "Dialogs": dialogs.md
  - "Spine": spine.md
