name: Python package prepare_assets

on: [push]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv install -d
          pipenv install pywin32-ctypes pefile
      - name: Build
        run: pipenv run pyinstaller --onefile .\prepare_assets.py
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: prepare_assets.exe
          path: dist\prepare_assets.exe
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
